build:
  maxIssues: 0

complexity:
  LongParameterList:
    ignoreAnnotated: ['Composable']
  LongMethod:
    ignoreAnnotated: ['Composable']

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']

style:
  MagicNumber:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']
  ReturnCount:
    max: 4
